### ISSUE TITLE
The left section (notes/ discussion) should scroll to the top when we switch pages

### ISSUE THREAD

**Issue by mithi** [mithi/epic-react-exercises#112]
We'd have to modify 

https://github.com/mithi/epic-react-exercises/blob/d62ff4cfaf54598eb6b4bfc518f176d10163bba8/components/notebook/index.js#L129

to scroll to the top on each re-render

**Comment by r002** [comment]
Hi!  Thank you so much for sharing your project.  I found it on Reddit!  Can you please assign this issue to me?  I'd like to contribute.  Thank you!  🙏🙏

**Comment by r002** [comment]
Hi! Thank you so much for sharing your project. I found it on Reddit! Can you please assign this issue to me? I'd like to contribute. Thank you! 🙏🙏

PS.  Also, you mean the "right" section ("notes/discussion"), correct?  That needs to scroll every time the page switches, right?

**Comment by r002** [comment]
For reference:

- https://stackoverflow.com/questions/33188994/scroll-to-the-top-of-the-page-after-render-in-react-js
- https://stackoverflow.com/questions/68165/javascript-to-scroll-long-page-to-div
